#!/bin/sh

kj p2

echo
echo RMB  "   1  24.994446"
echo RMB  "3234   0.014984"
echo
echo RMB  "10.7 secs"
echo
echo "--------------------------- 1 threads -----------------------------"
echo
/usr/bin/time -p  ./p2  1500 3000 100 100 100 400 0.015  1
echo
pwd
echo
